# Generated by Django 5.2 on 2025-07-12 14:54

import places.models
from django.db import migrations, models


def clear_place_images(apps, schema_editor):
    """Удаляет все записи PlaceImage перед созданием уникального ограничения"""
    PlaceImage = apps.get_model('places', 'PlaceImage')
    PlaceImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ["place", "order", "id"],
                "verbose_name": "Изображение места",
                "verbose_name_plural": "Изображения мест",
            },
        ),
        migrations.AddField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=places.models.place_image_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="placeimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок отображения изображения (0 - первое)",
                verbose_name="Порядок",
            ),
        ),
        migrations.RunPython(clear_place_images, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="placeimage",
            unique_together={("place", "order")},
        ),
        migrations.RemoveField(
            model_name="placeimage",
            name="image_url",
        ),
    ]
