# Generated by Django 5.2 on 2025-07-12 15:20

from django.db import migrations, models


def clear_null_images(apps, schema_editor):
    """Удаляет записи с пустыми изображениями"""
    PlaceImage = apps.get_model('places', 'PlaceImage')
    PlaceImage.objects.filter(image__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_alter_placeimage_options_and_more"),
    ]

    operations = [
        migrations.RunPython(clear_null_images, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(
                upload_to="places/",
                verbose_name="Изображение"
            ),
        ),
    ]
