# Generated by Django 5.2 on 2025-07-13 12:53

import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_make_image_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ["place", "order"],
                "verbose_name": "Изображение места",
                "verbose_name_plural": "Изображения мест",
            },
        ),
        migrations.AlterUniqueTogether(
            name="placeimage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(
                upload_to=places.models.place_image_path, verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок отображения изображения (заполняется автоматически)",
                verbose_name="Порядок",
            ),
        ),
    ]
