# Generated by Django 5.2 on 2025-07-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_place_description_long_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_short",
            new_name="short_description",
        ),
    ]
