# Generated by Django 5.2 on 2025-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_rename_description_long_place_long_description_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="placeimage",
            index=models.Index(fields=["place", "order"], name="place_order_idx"),
        ),
    ]
