# Generated by Django 5.2 on 2025-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_add_place_order_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название места"
            ),
        ),
    ]
